apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-server-deployment
  labels:
    app: my-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-server
  template:
    metadata:
      labels:
        app: my-server
    spec:
      containers:
        - name: my-server-container
          image: glibesyck/my-server:latest
          ports:
            - containerPort: 8000
