apiVersion: batch/v1
kind: Job
metadata:
  name: my-server-job
spec:
  template:
    spec:
      containers:
        - name: my-server-container
          image: glibesyck/my-server:latest
      restartPolicy: Never
