name: CI/CD - Docker Build & Push (HW2 PR2)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'module-1/hw-2/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t my-server module-1/hw-2/

      - name: Tag Docker image
        run: |
          docker tag my-server ${{ secrets.DOCKER_HUB_USERNAME }}/my-server:pr-${{ github.event.number }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-server:pr-${{ github.event.number }}
